
- name: Allow httpd write to data folder
  community.general.sefcontext:
    target: '{{ nc_data_dir }}(/.*)?'
    setype: httpd_sys_rw_content_t
    state: present
    
- name: Allow httpd write to config folder
  community.general.sefcontext:
    target: '/var/www/html/nextcloud/config(/.*)?'
    setype: httpd_sys_rw_content_t
    state: present
    
- name: Allow httpd write to apps folder
  community.general.sefcontext:
    target: '/var/www/html/nextcloud/apps(/.*)?'
    setype: httpd_sys_rw_content_t
    state: present

- name: Allow httpd write to .htaccess
  community.general.sefcontext:
    target: '/var/www/html/nextcloud/.htaccess'
    setype: httpd_sys_rw_content_t
    state: present
    
- name: Allow httpd write to .user.ini
  community.general.sefcontext:
    target: '/var/www/html/nextcloud/.user.ini'
    setype: httpd_sys_rw_content_t
    state: present

- name: Allow httpd write to 3rdparty/aws/aws-sdk-php/src/data/logs folder
  community.general.sefcontext:
    target: '/var/www/html/nextcloud/3rdparty/aws/aws-sdk-php/src/data/logs(/.*)?'
    setype: httpd_sys_rw_content_t
    state: present


- name: Apply new SELinux file context to nextcloud folder
  ansible.builtin.command: restorecon -R '/var/www/html/nextcloud/'
  
- name: Apply new SELinux file context to data folder
  ansible.builtin.command: restorecon -R '{{ nc_data_dir.split('/')[:-1] | join('/') }}'
  
- name: Set httpd_can_network_connect persistant flag 
  ansible.posix.seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
      
- name: Set httpd_unified persistant flag 
  ansible.posix.seboolean:
    name: httpd_unified
    state: yes
    persistent: yes
      
- name: Set httpd_can_network_connect_db persistant flag 
  ansible.posix.seboolean:
    name: httpd_can_network_connect_db
    state: yes
    persistent: yes

